CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    weight DECIMAL(10,2) NOT NULL,
    value DECIMAL(10,2) NOT NULL
);
